[[collection]]
type = "art"
title = "Tokio"
subtitle = "Sbutitle"
link = "https://example.com"
img = "https://cdn.deepseek.com/logo.png?x-image-process=image%2Fresize%2Cw_1920"
content = "Tokio is an asynchronous runtime for the Rust programming language. It provides the building blocks needed for writing network applications. It gives the flexibility to target a wide range of systems, from large servers with dozens of cores to small embedded devices."
footer = "Footer"

[[collection]]
type = "art"
title = "Tokio"
subtitle = "Sbutitle"
link = "https://example.com"
img = "https://cdn.deepseek.com/logo.png?x-image-process=image%2Fresize%2Cw_1920"
content = "Tokio is an asynchronous runtime for the Rust programming language. It provides the building blocks needed for writing network applications. It gives the flexibility to target a wide range of systems, from large servers with dozens of cores to small embedded devices."
footer = "Footer"

[[collection]]
type = "art"
title = "Tokio"
subtitle = "Sbutitle"
link = "https://example.com"
img = "https://cdn.deepseek.com/logo.png?x-image-process=image%2Fresize%2Cw_1920"
content = "Tokio is an asynchronous runtime for the Rust programming language. It provides the building blocks needed for writing network applications. It gives the flexibility to target a wide range of systems, from large servers with dozens of cores to small embedded devices."
footer = "Footer"

[[collection]]
type = "art"
title = "Tokio"
subtitle = "Sbutitle"
link = "https://example.com"
img = "https://cdn.deepseek.com/logo.png?x-image-process=image%2Fresize%2Cw_1920"
content = "Tokio is an asynchronous runtime for the Rust programming language. It provides the building blocks needed for writing network applications. It gives the flexibility to target a wide range of systems, from large servers with dozens of cores to small embedded devices."
footer = "Footer"

[[collection]]
type = "art"
title = "Tokio"
subtitle = "Sbutitle"
link = "https://example.com"
img = "https://cdn.deepseek.com/logo.png?x-image-process=image%2Fresize%2Cw_1920"
content = "Tokio is an asynchronous runtime for the Rust programming language. It provides the building blocks needed for writing network applications. It gives the flexibility to target a wide range of systems, from large servers with dozens of cores to small embedded devices."
footer = "Footer"