[[collection]]
type = "art_simple"
title = "Tokio"
subtitle = "Subtitle"
link = "https://example.com"
img = "https://cdn.deepseek.com/logo.png?x-image-process=image%2Fresize%2Cw_1920"

[[collection]]
type = "art_simple"
title = "Tokio"
subtitle = "Subtitle"
link = "https://example.com"
img = "https://cdn.deepseek.com/logo.png?x-image-process=image%2Fresize%2Cw_1920"

[[collection]]
type = "art_simple"
title = "Tokio"
subtitle = "Subtitle"
link = "https://example.com"
img = "https://cdn.deepseek.com/logo.png?x-image-process=image%2Fresize%2Cw_1920"

[[collection]]
type = "art_simple"
title = "Tokio"
subtitle = "Subtitle"
link = "https://example.com"
img = "https://cdn.deepseek.com/logo.png?x-image-process=image%2Fresize%2Cw_1920"

[[collection]]
type = "art_simple"
title = "Tokio"
subtitle = "Subtitle"
link = "https://example.com"
img = "https://cdn.deepseek.com/logo.png?x-image-process=image%2Fresize%2Cw_1920"

[[collection]]
type = "art_simple"
title = "Tokio"
subtitle = "Subtitle"
link = "https://example.com"
img = "https://cdn.deepseek.com/logo.png?x-image-process=image%2Fresize%2Cw_1920"